# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  major: '1'
  minor: '0'
  revision: $[counter(variables['minor'], 1)] # This will get reset every time minor gets bumped.
  nugetVersion: '$(major).$(minor).$(revision)'

steps:
- script: echo $(nugetVersion)

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    publishTestResults: true
    configuration: $(buildConfiguration)

- script: dotnet publish -o $(build.artifactStagingDirectory)
  displayName: 'dotnet publish -o $(build.artifactStagingDirectory)'

- task: NuGetAuthenticate@0
  inputs:
    nuGetServiceConnections: nuget-srd-infra
# - task: NuGetCommand@2
#   inputs:
#     command: push
#     nuGetFeedType: external
#     versioningScheme: byEnvVar
#     versionEnvVar: <VERSION_ENVIRONMENT_VARIABLE>

# - task: DotNetCoreCLI@2
#   displayName: 'dotnet publish'
#   inputs:
#     command: 'publish'
#     publishWebProjects: false
#     projects: '**/*.csproj'
#     configuration: $(buildConfiguration)
#     zipAfterPublish: false