trigger:
- none

# Pipeline resource defined as per https://bit.ly/3PhwhRk
resources:
  pipelines:
  - pipeline: build_pipeline        # Used to reference the pipeline reference from other parts of the code.
    source: infra_build_pipeline  	# This must match  the build pipeline name in ADO.
                                    # By default, pipelines are named after the repository that contains the pipeline.
    trigger:
      branches:
      - master                      # Will get triggered whenever the source pipeline runs on master branch.

jobs:
- deployment: infra_deploy_to_nuget
  displayName: Deploy to NuGet
  environment: production
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    runOnce:
      deploy:
        steps:
        - download: none
        # - download: Build/infra_build_pipeline #tu ide ime build pipelinea?
        #   artifact: drop
        #   displayName: "Download build artifact"

        # - task: ExtractFiles@1
        #   inputs:
        #     archiveFilePatterns: '$(PIPELINE.WORKSPACE)/drop/$(resources.pipeline.myappbuild.runID).zip'

        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'specific'
            definition: infra_build_pipeline
            buildVersionToDownload: 'latest'
            artifactName: 'drop'
            project: 'SRD.Infrastructure'
            downloadPath: '$(Pipeline.Workspace)/drop'
          
        - script: ls -al ../
          displayName: 'ls ../'
          
        - script: ls -al ../drop
          displayName: 'ls ../drop'
          
        - script: ls -al ../drop/a
          displayName: 'ls ../drop/a'
          
        - script: ls -al ../drop/b
          displayName: 'ls ../drop/b'
          
        - script: ls -al ../drop/s
          displayName: 'ls ../drop/s'

        # - script: dotnet nuget push $(Pipeline.Workspace)/drop/SparkRoseDigital.Infrastructure.$(resources.pipeline.build_pipeline.runID).nupkg --api-key $(nuget_api_key) --source https://api.nuget.org/v3/index.json
        #   displayName: 'dotnet nuget push'
