trigger:
- none

resources:
  pipelines:
  - pipeline: infra_release_pipeline  #what the hell is this?
    source: infra_build_pipeline
    trigger:
      branches:
      - master

jobs:
- deployment: infra_deploy_to_nuget
  displayName: Deploy to NuGet
  environment: production
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    runOnce:
      deploy:
        steps:
        - download: infra_build_pipeline #tu ide ime build pipelinea?
          artifact: drop
        # - task: ExtractFiles@1
        #   inputs:
        #     archiveFilePatterns: '$(PIPELINE.WORKSPACE)/drop/$(resources.pipeline.myappbuild.runID).zip'

        # ovo ne treba, jer deploy job sam downloada.
        # - task: DownloadPipelineArtifact@2
        #   inputs:
        #     buildType: 'current'
        #     artifactName: 'drop'
        #     downloadPath: '$(Pipeline.Workspace)/drop'
