trigger:
- none

resources:
  pipelines:
  - pipeline: infra_release_pipeline
    source: infra_build_pipeline  	# this must match  the build pipeline name in ADO.
    trigger:
      branches:
      - master

jobs:
- deployment: infra_deploy_to_nuget
  displayName: Deploy to NuGet
  environment: production
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    runOnce:
      deploy:
        steps:
        - download: infra_build_pipeline #tu ide ime build pipelinea?
          artifact: drop
          displayName: "Download build artifact"

        # - task: ExtractFiles@1
        #   inputs:
        #     archiveFilePatterns: '$(PIPELINE.WORKSPACE)/drop/$(resources.pipeline.myappbuild.runID).zip'
        # - task: DownloadPipelineArtifact@2
        #   inputs:
        #     buildType: 'current'
        #     artifactName: 'drop'
        #     downloadPath: '$(Pipeline.Workspace)/drop'
        - script: dotnet nuget push $(Pipeline.Workspace)/drop/SparkRoseDigital.Infrastructure.$(resources.pipeline.infra_release_pipeline.runID).nupkg --api-key $(nuget_api_key) --source https://api.nuget.org/v3/index.json
          displayName: 'dotnet nuget push'
