trigger: none
pr: none

# Pipeline resource defined as per https://bit.ly/3PhwhRk
resources:
  pipelines:
  - pipeline: build_pipeline        # Used to reference the pipeline reference from other parts of the code.
    source: infra_build_pipeline  	# This must match  the build pipeline name in ADO.
                                    # By default, pipelines are named after the ADO build pipeline name.
    trigger:
      branches:
      - master                      # Will get triggered whenever the source pipeline runs on master branch.

jobs:
- deployment: infra_deploy_to_nuget
  displayName: Deploy to NuGet
  environment: production
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    runOnce:
      deploy:
        steps:
        - download: none
        
        - script: |
            echo resources.pipeline.build_pipeline.projectName 
            echo resources.pipeline.build_pipeline.projectID 
            echo resources.pipeline.build_pipeline.pipelineName 
            echo resources.pipeline.build_pipeline.pipelineID 
            echo resources.pipeline.build_pipeline.runName 
            echo resources.pipeline.build_pipeline.runID
            echo resources.pipeline.build_pipeline.runURI
            echo resources.pipeline.build_pipeline.sourceBranch 
            echo resources.pipeline.build_pipeline.sourceCommit
            echo resources.pipeline.build_pipeline.sourceProvider 
            echo resources.pipeline.build_pipeline.requestedFor
            echo resources.pipeline.build_pipeline.requestedForID

        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'specific'
            definition: infra_build_pipeline
            buildVersionToDownload: 'latest'
            artifactName: 'drop'
            project: 'SRD.Infrastructure'
            downloadPath: '$(Pipeline.Workspace)/drop'

        - script: dotnet nuget push $(Pipeline.Workspace)/drop/a/SparkRoseDigital.Infrastructure.*.nupkg --api-key $(nuget_api_key) --source https://api.nuget.org/v3/index.json
          displayName: 'dotnet nuget push'